---
- name: Ensure hwclock is installed
  package:
    name:
      - util-linux-extra # hwclock is not installed by default in Ubuntu 24.04LTS
    state: present
  become: yes

- name: Install systemd-timesyncd
  package:
    name: systemd-timesyncd
  when: not ((ansible_distribution == 'Debian' and ansible_distribution_major_version is version('11', '<')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version('20', '<')) or ansible_distribution == 'Archlinux')

- name: Set timezone
  timezone:
    name: "{{ timesync_timezone }}"
  notify: systemd-timesyncd configuration changed

- name: Create systemd-timesyncd.conf.d
  file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf.d/local.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
